
.PHONY: all clean cleanall

all:
	@$(MAKE) all -C c_vals
	@$(MAKE) all -C c_string
	@$(MAKE) all -C saturation
	@$(MAKE) all -C array_view

clean:
	@$(MAKE) clean -C c_vals
	@$(MAKE) clean -C c_string
	@$(MAKE) clean -C saturation
	@$(MAKE) clean -C array_view

cleanall:
	@$(MAKE) cleanall -C c_vals
	@$(MAKE) cleanall -C c_string
	@$(MAKE) cleanall -C saturation
	@$(MAKE) cleanall -C array_view
